
name: Executable Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    
      # Check-out repository
      - uses: actions/checkout@v3
      
      # Setup Python
      - uses: actions/setup-python@v4
        timeout-minutes: 10
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@main
        timeout-minutes: 30
        with:
          script-name: __init__.py
          # access-token: ${{ secrets.NUITKA_COMMERCIAL_ACCESS_TOKEN }}
          onefile: true
          enable-plugins: pyqt5
          disable-console: false
          # TODO: 图标设置
          # windows-icon-from-ico: resources/app.ico
          macos-create-app-bundle: true
          
      # Uploads artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            